# Generated by Django 4.2.4 on 2023-08-04 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_name', models.CharField(max_length=100)),
                ('consultation_taken_time', models.DateTimeField()),
                ('user_problem', models.CharField(max_length=5000)),
                ('current_solution', models.TextField(blank=True, null=True)),
                ('current_solution_given_time', models.DateTimeField(blank=True, null=True)),
                ('solution_given_time', models.DateTimeField(blank=True, null=True)),
                ('current_solution_given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_number', models.PositiveIntegerField()),
                ('solution_text', models.TextField()),
                ('given_time', models.DateTimeField(auto_now_add=True)),
                ('Consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ConsultationHistory', to='consultation.consultation')),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-given_time'],
            },
        ),
    ]
