# Generated by Django 4.2.4 on 2023-08-08 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_remove_useraccount_is_user_useraccount_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsultationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_name', models.CharField(max_length=255)),
                ('consultation_created_time', models.DateField(default=django.utils.timezone.now)),
                ('consultation_details', models.TextField(blank=True, max_length=2000, null=True)),
                ('consultation_status', models.CharField(default='Pending', max_length=255)),
                ('consultation_solutation_given_time', models.DateField(default=django.utils.timezone.now)),
                ('consultation_solutation_given_by', models.CharField(blank=True, max_length=255, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
