# Generated by Django 4.2.4 on 2023-08-08 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_userconsultationdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsultationdetails',
            name='consultation_created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userconsultationdetails',
            name='consultation_solutation_given_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
