# Generated by Django 4.2.4 on 2023-08-08 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_rename_consultation_solutation_given_time_userconsultationdetails_consultation_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsultationdetails',
            name='consultation_solution',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='userconsultationdetails',
            name='consultation_solution_given_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
