# Generated by Django 4.2.4 on 2023-08-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_alter_userconsultationdetails_consultation_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsultationdetails',
            name='consultation_solution',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
