# Generated by Django 4.2.4 on 2023-08-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_alter_userconsultationdetails_consultation_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsultationdetails',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
